---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/maicon65/maiconbotelho.com.br/
    - /bin/cp -R .next $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - cd $DEPLOYPATH && npm install
    - cd $DEPLOYPATH && npm run build
