import NavBar from '@/components/navBar';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Maicon Botelho | Home',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt" className="dark">
      <body
        className={`px-8 md:px-12 lg:px-16 xl:px-24 ${montserrat.className}`}
      >
        <>
          <NavBar />

          {children}
        </>
      </body>
    </html>
  );
}
